### ISSUE TITLE
Is this dataset still expected to be released?

### ISSUE THREAD

**Issue by kartheekmedathati** [mosaicml/diffusion#137]
Wondering if this is scheduled to be released or abandoned?

**Comment by Skylion007** [comment]
Yeah, we ran into some initial hosting issues, but have been working with HuggingFace to resolve them. I just started my initial attempt to upload the full dataset.

**Comment by Skylion007** [comment]
I've now nearly uploaded 2/6 splits subsets. HF going down this past week definitely didn't help lol.

**Comment by ferarn** [comment]
> > I've now nearly uploaded 2/6 splits subsets. HF going down this past week definitely didn't help lol.
> 
> do you have the link to the dataset? or where the dataset will be?

My guess would be on his or mosaicml's HF page based upon his last statement:
- https://huggingface.co/Skylion007
- https://huggingface.co/mosaicml

I'm trying to learn more about Lora's and Embeddings beforehand in order to hopefully merge and train ethical add-ons and checkpoints with it that'll catch on on Civitai, cause then we'd finally have an ethical model base in a readily available source, if the terms and architecture allow it.

**Comment by Dibbidy** [comment]
> I've now nearly uploaded 2/6 splits subsets. HF going down this past week definitely didn't help lol.

Can we expect an update?

**Comment by Dibbidy** [comment]
> I've now nearly uploaded 2/6 splits subsets. HF going down this past week definitely didn't help lol.

is there any update on this @Skylion007

**Comment by nunbuzor** [comment]
> * [](https://huggingface.co/mosaicml)
> 
> I'm trying to learn more about Lora's and Embeddings beforehand in order to hopefully merge and train ethical add-ons and checkpoints with it that'll catch on on Civitai, cause then we'd finally have an ethical model base in a readily available source, if the terms and architecture allow it.

hope we can finetune it with this high quality dataset: https://www.kaggle.com/datasets/innominate817/pexels-110k-768p-min-jpg/data
