### ISSUE TITLE
FID and CLIP score

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#21]
Hope this finds you well. Nice work.
One quick question: have you compared the FID/CLIP score of mosaic diffusion-2.0-base and the official diffusion-2.0-base? 
I only find some human evaluation results shown in https://www.mosaicml.com/blog/training-stable-diffusion-from-scratch-part-2.

**Comment by DiegoD94** [comment]
Following up on this, do we have a CLIP/FID score curve along the training that you can share? Thanks!

**Comment by Landanjs** [comment]
We are wrapping up our FID / CLIP score calculations over the weekend. We will post results early next week!

**Comment by viyjy** [comment]
Thanks. The FID/CLIP score evaluated during the model training is not correct. For instance, the FID is 1.5 and CLIP is 15 which are evaluated at 10k steps.

**Comment by Landanjs** [comment]
Below is our FID vs CLIP score comparison to Stable Diffusion 2.0 base. The evaluation is calculated using [clean-fid](https://github.com/GaParmar/clean-fid) on 30k random caption samples from the COCO 2014 eval dataset. The generated images were at 512x512 resolution. For the real COCO images, we preserve aspect ratio and resize the smallest size to be 512, then take a center crop. We re-evaluated Stable Diffusion 2.0 base since FID is very sensitive to small details in evaluation, hence the difference from their reported FID value.

Addressing #32, COCO 2017 eval only has 5k images, restricting the number of samples you can use to calculate FID. Since FID is significantly impacted by the number of samples, we decided to use COCO 2014 eval which has 41k samples and has been used in previous papers. 

There are many possible reasons for the difference in our FID value, but the most likely culprit is data. For instance, Stability did dataset filtering based on watermarks and unsafe content. Two other possibilities are caption drop rate and weight decay since we could not find exact values for these. We also need to measure error bars to determine if the difference is statistically significant.

In any case, FID on COCO evaluates a limited set of model capabilities (i.e. generating photorealistic images of a restricted set of objects). We opted for human evaluation since this tests a wider set of model capabilities such as composition, knowledge, etc.

![clean-fid-base](https://github.com/mosaicml/diffusion/assets/33618586/4dfb8a5c-1c14-4541-a758-7f57de36ee5e)

**Comment by viyjy** [comment]
Many thanks, very helpful!!!

**Comment by viyjy** [comment]
@Landanjs, since clean-fid reports `FID` and `CLIP-FID`, which score do you use in your figure? Thanks.
