### ISSUE TITLE
Throughput is low

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#34]
Hi, I am using 16 nodes, each of which has 8 A100s to train the first stage (256x256) of sd-2.0-base.
The total batch size is 2048=128*16. I am not using pre-computed latents, giving the throughput about 5.5k-6K samples/sec.
As mentioned [here](https://github.com/mosaicml/diffusion#how-many-gpus-do-i-need), the throughput of your model training is 11600 samples/sec by using pre-computed latents. Given the following estimation, the throughput of your model training is about 11600/1.4=8286 samples/sec without using pre-computed latents. This throughput is quite higher than ours, any ideas? Thanks.
> If you are computing VAE and CLIP latents while training, expect a 1.4x increase in time and cost.

**Comment by mvpatel2000** [comment]
@viyjy  can you please share your config? Can you confirm you enabled all of the speedups? 

The exact speedup is likely higher if you are only comparing against the final time. This is because the additional methods further speed up the U-Net step, but the total throughput will still be slow even if the U-Net is sped up all the way if the VAE/CLIP times are present.

As an illustration:
VAE time = 1s, UNet time = 1s, CLIP time = epsilon

1. Remove VAE = 2x speedup, total time = 1s
2. Next, 2x speedup U-Net = 2x speedup, total time = 0.5s, total speedup = 4x

However, without step 1, it becomes
1. 2x speedup U-Net = 1.5x speedup, total time = 1.5s

So, it might not be a reasonable estimate to use the 1.4x number....

**Comment by mvpatel2000** [comment]
@viyjy  I would expect you would have significant slowdown in image decoding. I recommend profiling it to see how much time that takes.

**Comment by viyjy** [comment]
I see, thanks.
