### ISSUE TITLE
Weights for the trained model

### ISSUE THREAD

**Issue by nisargshah1999** [mosaicml/diffusion#5]
Can you share the weight for the trained model
Also, is there any technical report to understand, the building blocks, that can quantify improvements

**Comment by mvpatel2000** [comment]
@nisargshah1999 Unfortunately, due to the [legal issues](https://www.theverge.com/2023/1/17/23558516/ai-art-copyright-stable-diffusion-getty-images-lawsuit) around LAION, the dataset used to train Stable Diffusion, we are unable to release weights. 

We'll be doing a follow-up blog post very soon going into more detail on the exact speedup methods and how much they each contribute to faster training. Stay tuned!

**Comment by yhyu13** [comment]
What about delta weights walk around ?
![313BD7EC](https://user-images.githubusercontent.com/19365678/236097113-ca0d482a-dffd-4c12-a694-470e8b261c35.png)
