### ISSUE TITLE
Any plan to support "Emu: Enhancing Image Generation Models Using Photogenic Needles in a Haystack"?

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#83]
Hi, do you have plan to support [EMU](https://ai.meta.com/research/publications/emu-enhancing-image-generation-models-using-photogenic-needles-in-a-haystack/)? According to the paper, this model outperforms SDXL and only requires 2k images for quality-tuning. The images showcased in the paper is very realistic

**Comment by jazcollins** [comment]
Architecturally, it sounds like the model they train is very similar to SDXL, which we recently have added support for in this repo.

They use a slightly larger U-Net than SDXL, although I don't see detail in the paper on the exact architectural changes (just mention of more channels and residual blocks), however, the U-Net architecture can easily be modified by changing the  config passed [here](https://github.com/mosaicml/diffusion/blob/main/diffusion/models/models.py#L205). They also use T5-XXL instead of OpenCLIP ViT-bigG, which I think should also be a matter of passing a different text encoder config.

The experimental results seem to suggest that the real value comes from the highly curated 2K images that they fine-tune on, which as I understand they did not release :) So without those images, I suspect that training SDXL (which we do support) would be comparable to their pre-fine-tuning model.

**Comment by viyjy** [comment]
Thanks!
